name: GBA ROM Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: bw

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python3-version: '3.9'

    - name: Install devkitARM
      run: |
        sudo apt-get update
        sudo apt-get install -y wget bzip2
        wget https://github.com
        sudo apt-get install ./devkitpro-pacman.amd64.deb
        sudo dkpro-pacman -Syy --noconfirm
        sudo dkpro-pacman -S gba-dev --noconfirm
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "/opt/devkitpro/devkitARM/bin" >> $GITHUB_PATH

    - name: Run Build Script
      run: |
        python scripts/make.py

    - name: Upload Finished ROM
      uses: actions/upload-artifact@v4
      with:
        name: Finished-BW-StartMenu-ROM
        path: test.gba
